### ISSUE TITLE
Add Gallery Figures to Pages in the Historical Section

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/florence-kelley#11]
We are using a Gallery plugin to display images on the pages. The gallery code needs to be added to the end of the `.md` files for the pages where the gallery will be displayed.

Here's the gallery code template:
```
{{< gallery >}}
  {{< figure link="/img/galleries/historical/[filename].jpg" caption="[Caption text]" >}}
  {{< figure link="/img/galleries/historical/[filename].jpg" caption="[Caption text]" >}}
  {{< figure link="/img/galleries/historical/[filename].jpg" caption="[Caption text]" >}}
  {{< figure link="/img/galleries/historical/[filename].jpg" caption="[Caption text]" >}}
{{< /gallery >}}{{< load-photoswipe >}}
```

Use the [fk_photos spreadsheet](https://northwestern.box.com/s/15vxc6cd423vrr5ges115pbzkjveifg7) to find the `filename` and `caption` for the figures. The `page` column refers to the name of the `.md` file in the `/content/historical/` directory. Every row in the spreadsheet refers to a `{{< figure >}}` element wrapped in the `{{< gallery >}}` element.

These are the pages that need gallery figures added:
- altgeld.md
- haymarket.md
- hullhouse.md
- iriquois.md
- jts.md
- mayer.md
- panic.md

You can look at the other `.md` files in the `historical` directory to see examples of what the gallery figures code looks like.

**Comment by echoe320** [comment]
fixed in #13
