### ISSUE TITLE
Add PDF download paths to pages in Archives section

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/florence-kelley#14]
The files in `/content/archives/` contain links that are intended to trigger PDF downloads. The PDFs are stored in `/static/fk_documents/`. 

The url part of the markdown links need to be updated to point to the document in the `/fk_documents/` directory. This is the template for each link:

```
[Title of Document](/fk_documents/filename.pdf)
```

For example, this line in the table:

```
2007 | [History of Chicago (Vol. 3: The Rise of a Modern City, 1871-1893)](2007. Pierce, Bessie Louise. University of Chicago Press Copyright 2007 University of Chicago Press.)
```

should be changed to:

```
2007 | [History of Chicago (Vol. 3: The Rise of a Modern City, 1871-1893)](/fk_documents/fk_04755641_03.pdf)
```

You can find the PDF filenames based on their titles from the [fk_documents](https://northwestern.box.com/s/d5w8g37kde5w07nfwy0qf6h1ayghcwff) spreadsheet.

These are the pages in `/content/archives/` that need updated links:
- book.md
- congressional.md
- correspondence.md
- court.md
- dissertation.md
- factory.md
- government.md
- kelley.md
- newspaper.md
- periodical.md

### Done looks like it
The links in those pages point to PDF documents in `/fk_documents/` based on the spreadsheet.

**Comment by echoe320** [comment]
fixed in #19
