### ISSUE TITLE
Adds url info to related_content on historical/timeline

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/florence-kelley#16]
In `/content/historical/timeline.md`, the `related_content` front matter of the markdown file is missing URL values. Use the [fk_documents](https://northwestern.box.com/s/d5w8g37kde5w07nfwy0qf6h1ayghcwff) spreadsheet to find the `url` info for each corresponding `title` value.

**Comment by echoe320** [comment]
fixed in #21
